### PR TITLE
Savannah Huntress: Remove UNIT_STAND_STATE_SLEEP for creatures with random movement

### PR DESCRIPTION
**Pull request by ghost**
## 🍰 Pullrequest
Remove stand state for four of the Savannah Huntresses.

### Proof
None

### Issues
Four of the Savannah Huntresses use UNIT_STAND_STATE_SLEEP and random movement at the same time which looks strange.

### How2Test
```
.go cr 14119
.go cr 14117
.go cr 14116
.go cr 14108
```

### Todo / Checklist
- [X] None

### CODE REVIEW

**Comment by Daribon** [comment]
Have you checked in sniffs if they use UNIT_STAND_STATE_SLEEP?

**Comment by ghost** [comment]
No, I just quested there and saw that their movement looks weird.

**Comment by ratkosrb** [comment]
Why not check these mobs on classic to see whats correct?

**Comment by ghost** [comment]
Sorry, but I cannot check this on classic. Did not touch my battle.net account since 2011.

**Comment by ghost** [comment]
Not needed.

**Pull request closed without merging**
