### PR TITLE
Fix Westfall Lumbermill Event

### PR DESCRIPTION
**Pull request by NickTyrer**
This PR adds the creature_movement_script to the correct waypoint and removes an unneeded waypoint.

### CODE REVIEW

**Comment by ratkosrb** [comment]
The last waypoint is a delay before repeating the path. You had it made so the delay is in EventAI, but this is not the proper way to do it. You should not assign EventAI to a NPC only to have a timer that starts waypoints periodically. You don't need EventAI here at all. You just need to move the delay to a waypoint. That's what I did.

**Comment by NickTyrer** [comment]
@ratkosrb OK will do that in future. The script has to be on the last waypoint otherwise the npc's orientation will be wrong.

**Comment by ratkosrb** [comment]
Does the script execute correctly if it is on the last wp? I was afraid it would execute after the delay is over, instead of when arriving.

**Comment by NickTyrer** [comment]
@ratkosrb It executes correctly with this PR.

**Pull request merged**
