### PR TITLE
Update and add NPC movement scripts - WPL

### LINKED ISSUE #637: NPC Bug Scarlet Lumberjack
**Current behavior**: 
The NPC's are static in northridge lumber camp

**Expected behavior**: 
Some of the mobs should have the chop wood animation see:
https://youtu.be/laHIvE5hH58

**Client version**: 
1.12.1
**Commit hash**: 
ab11bde
**Operating system**: 
Win 10

### PR DESCRIPTION
**Pull request by NickTyrer**
Fixes #637

### CODE REVIEW

**Comment by ratkosrb** [comment]
Does setting talk emote in creature_addon actually do something? Because this is supposed to for emote states, not one-shot emotes.

**Comment by NickTyrer** [comment]
@ratkosrb yes it works.

**Comment by ratkosrb** [comment]
Do they really repeat it over and over with no delay on classic?

**Comment by NickTyrer** [comment]
No, they have a delay. Is there any way to set this through creature_addon or do I need to add an event?

**Comment by ratkosrb** [comment]
No, you have to use EventAI. Are the npcs who do talk emotes in pairs? In this case you can have a OOC timer with NEARBY_CREATURE condition assigned, so they only talk when they have a buddy next to them.

**Comment by NickTyrer** [comment]
Could I implement it like I did here (https://github.com/vmangos/core/pull/664/files# LINE 995)?

**Comment by ratkosrb** [comment]
Yes, a guid condition works too.

**Pull request merged**
