### PR TITLE
Fix movement issue for npc 1502

### LINKED ISSUE #395: Random movement issue: Wretched Zombie (id: 1502)
Random movement animation of npc 1502 is broken.
(old issue, I saw this ages ago)

**Steps to reproduce**:
1.  .tele deathknell
2.  watch random movement of Wretched Zombie
3.  sometimes npc does its walking animation, but the npc is not moving.

npc-1502-broken-movement

**Client version**: 
1.12.1 5875
**Commit hash**: 
645a642
**Operating system**: 
Win 10

### PR DESCRIPTION
**Pull request by schell244**
Fixed by removing ai_name parameter from npc 1502.
(previously ai_name=EventAI was set)
Closes: https://github.com/vmangos/core/issues/395

### CODE REVIEW

**Comment by ratkosrb** [comment]
So you are saying it's caused by casting spell 26047?

**Comment by schell244** [comment]
If EventAI for npc 1502 is linked to spell 26047, than thats the issue. Afte removing EventAI, the npc did no longer 'walk on the spot', and everything else worked normal. I guess spell 26047 should actually do some kind of 'spawn out of the ground' animation?

**Comment by ratkosrb** [comment]
https://classicdb.ch/?spell=26047

**Comment by schell244** [comment]
Ok, so I'll close this PR and adapt the ticket #395 for fixing the spell?

**Comment by ratkosrb** [comment]
No, I think using the spell is wrong. I think it's only meant for ghouls (this npc uses ghoul model in wotlk, and mangos tbc and vanilla databases were downgraded from wotlk long time ago).

**Comment by schell244** [comment]
Ok, that looks cleaner. Thanks

**Pull request merged**
