### PR TITLE
Enable GM to modify player's rank points online.

### PR DESCRIPTION
**Pull request by lbcheng888**
setrp changes owner's rank point only ,while modify could change player's and owner's.

### CODE REVIEW

**Comment by ratkosrb** [comment]
This is the same thing _.honor setrp_ does.
https://github.com/vmangos/core/blob/development/src/game/Commands/CharacterCommands.cpp#L2200

**Comment by lbcheng888** [comment]
setrp only changes the owner's, modify can change player's and owner's.

**Comment by ratkosrb** [comment]
I updated the other command to target other players.

**Comment by lbcheng888** [comment]
Cool, I have checked, good fix!

**Pull request closed without merging**
