### PR TITLE
Add Some Missing Creature Spawns

### PR DESCRIPTION
**Pull request by NickTyrer**
### Todo / Checklist
- [ ] Add Spawns From Cmangos
- [ ] Check Existing Spawns that are pooled and have movement_type 2 are using creature_movement not creature_movement_template

### CODE REVIEW

**Comment by Kittnz** [comment]
Do not forget, cmangos also has a lot of manual spawned mobs. I suggest you work from sniff data instead.

**Comment by NickTyrer** [comment]
The sniff data doesnt have the correct spawn points if the creature is roaming, unless the sniffer saw the mob spawn. If we know the creature spawns in multiple locations I think we should use cmangos data.

**Comment by ratkosrb** [comment]
The cmangos db does not have the exact spawn coordinates of wandering mobs either, there is no way to get those unless you see the mob spawn as you said. You can just look at the positions the mob has been seen at, and pick a spot in the middle. Their guess is no more correct than ours. And it does not really matter when the mob is wandering, people will never see it at the exact position it spawns, it makes no difference if the spawn point is half a yard off, since the mob does not sit still anyways.

**Comment by NickTyrer** [comment]
So what is the problem using cmangos data if we know the mob spawns near an area?

**Comment by ratkosrb** [comment]
I listed you the problems already when we talked in discord.
- There were many manual spawns added in mangos back in the day, and even people adding completely made up waypoints to mobs, such as [this](https://github.com/vmangos/core/issues/1311) case. So you cannot just query missing or different spawns in their db and trust that to be authentic. Same way you cannot guarantee existing data we have is correct without checking sniffs.
- The vmangos and cmangos database have a common root, and they were down ported from TBC, which was downported from WotLK.
- The main developers of cmangos are focused on TBC, and Vanilla is merely an afterthought. The vast majority of commits in the classic db are simply ported from the TBC and WotLK repositories.
- None of the cmangos developers had any original Vanilla sniffs, so any work done prior to 2019 when Classic released, is based on TBC and WotLK sniffs.
- There were multiple changes made to the Vanilla world in TBC and WotLK. Elite areas were nerfed. New quests and npcs were added. Specific npcs were moved to a different place. Some mobs were removed and replaced with different ones. You cannot trust data from TBC to be correct for Classic. There are multiple places with different spawns i can mention off the top of my head that I've spent time to revert to their correct Vanilla state (quest givers in ashenvale, battlemasters in most cities, the majority of dustwallow marsh, many spawns in blasted lands...). If you were to start blindly replacing our spawns with cmangos classic-db data, you will revert most of these to their TBC state!

If you want to port spawns from cmangos, you must contact the people who added them and inquire what their source was on a case by case basis. If the work was based on 1.13 data, then you can port it. If it was based on TBC and WotLK sniffs they had, then you have to actually verify everything to make sure it's correct for Vanilla. Either go to that spot in the official Classic-Era (**NOT Classic-TBC**) servers, or look in the sniff db if we have any spawns near those coordinates.

**Comment by NickTyrer** [comment]
Ok, I give up.

**Pull request closed without merging**
