### PR TITLE
More database connection changes

### PR DESCRIPTION
**Pull request by 0blu**
## 🍰 Pullrequest

- Use `std::string` instand of `const char*` for `SqlConnection::Query`, although there are still many references to a raw char* left :/
- Rename config `MaxPingTime` to `Database.AliveCheckInternal` and make it an interval in seconds

### CODE REVIEW

**Comment by Gamemechanicwow** [comment]
What is the point in using std::string - if we don't use std::string functionality? Looks like it's just gonna add overhead and bloated asm.

**Comment by 0blu** [comment]
I mean was copied here anyways previously 
https://github.com/vmangos/core/pull/2651/files#diff-679bb7c6e8ba802a2e1c878b99891cdc7a39c96d1900d1b3a9bf5f80c80fdf6dL203

and I wanted to get rid of this code

https://github.com/vmangos/core/pull/2651/files#diff-679bb7c6e8ba802a2e1c878b99891cdc7a39c96d1900d1b3a9bf5f80c80fdf6dL233-L241

But maybe I can also reduce this pr to only the `Database.AliveCheckInternal` change.

**Comment by Gamemechanicwow** [comment]
> I mean was copied here anyways previously https://github.com/vmangos/core/pull/2651/files#diff-679bb7c6e8ba802a2e1c878b99891cdc7a39c96d1900d1b3a9bf5f80c80fdf6dL203

Aha, I missed that. But is that mangos_strdup() even needed? 🤔

**Comment by 0blu** [comment]
Yeah, otherwise you would try delete a `const char*` that is embedded in the binary `.rodata` section. (which will cause a segfault)

**Comment by Gamemechanicwow** [comment]
> Yeah, otherwise you would try delete a `const char*` that is embedded in the binary `.rodata` section. (which will cause a segfault)

Aren't we already doing that fine? Its a `char const*` in the pair.
        typedef std::pair<char const*, QueryResult*> SqlResultPair;

**Comment by 0blu** [comment]
Yes, it worked fine but you had to manually use `mangos_strdup` **and** `delete` that way.

**Pull request merged**
