### PR TITLE
🍰 [WIP] Quality Colors for GetItemLink & ItemLookup

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

Exploring the forks I stumbled upon this change. It seems to implement coloring of items by their respective quality looked up via command. Would this be useful?

### Proof

- None

### Issues

- None

### How2Test

- `.lookup cloth`

### Todo / Checklist

- [ ] Evaluate if we want this
- [ ] Evaluate if it works properly
- [x] Contact author for additional insights @Orozxy
- [ ] Clean Code if needed

### CODE REVIEW

**Comment by Oroxzy** [comment]
the one for itemlink in chat via .look item command is broken. you can't shift click anymore. needs a fix first

**Comment by ulfgebhardt** [comment]
Would you be willing to provide that fix? @Oroxzy

**Comment by Oroxzy** [comment]
Untitled

**Comment by ulfgebhardt** [comment]
I assume that is the problem you are describing @Oroxzy - is there a way to fix?
Could you also provide screenshots of the working part?

**Comment by Oroxzy** [comment]
i'll check later :)

**Comment by ulfgebhardt** [comment]
Here someone did something similar, maybe that helps

https://github.com/vmangos/core/compare/development...solo0755:development#diff-c4e25a68281b721ec0726583cc0dc8df1dba3100ffe0abe4bc24c011f39b4658R2614

https://github.com/vmangos/core/compare/development...solo0755:development#diff-c4e25a68281b721ec0726583cc0dc8df1dba3100ffe0abe4bc24c011f39b4658R2885

**Comment by Oroxzy** [comment]
> 
> 
> Here someone did something similar, maybe that helps
> 
> [development...solo0755:developmentdiff-c4e25a68281b721ec0726583cc0dc8df1dba3100ffe0abe4bc24c011f39b4658R2614](https://github.com/vmangos/core/compare/development...solo0755:developmentdiff-c4e25a68281b721ec0726583cc0dc8df1dba3100ffe0abe4bc24c011f39b4658R2614)
> 
> [development...solo0755:developmentdiff-c4e25a68281b721ec0726583cc0dc8df1dba3100ffe0abe4bc24c011f39b4658R2885](https://github.com/vmangos/core/compare/development...solo0755:developmentdiff-c4e25a68281b721ec0726583cc0dc8df1dba3100ffe0abe4bc24c011f39b4658R2885)

can't see this if i open the links, is it broken somehow?

**Comment by ulfgebhardt** [comment]
I am very sorry - github links break there apparently:
https://github.com/vmangos/core/compare/development...solo0755:development

image
image

Search for `GetItemLinkWithColoer`

Pinging the Author: @solo0755

**Comment by ulfgebhardt** [comment]
@Oroxzy How is the status on this particular PR? You added unrelated commits to your branch.
Thanks for your contributions <3

**Comment by Oroxzy** [comment]
ah sorry im so bad with git.. idk what im doing,

**Comment by ulfgebhardt** [comment]
make a branch for each change and PR from that branch ;)

**Comment by Oroxzy** [comment]
How can i remove the last 2 changes?

**Comment by ulfgebhardt** [comment]
make a new branch and apply only the two commits you want to it - open a new PR once you pushed your branch. I can recommend [smartgit](https://www.syntevo.com/smartgit/) if you want to use an GUI

The easiest way would be:
1. check out the last correct commit
2. Make a new branch from there
3. Push the branch to your fork
4. Make a new PR to vmangos from your fork

**Comment by Oroxzy** [comment]
https://github.com/Oroxzy/core/tree/Oroxzy-itemlinkcolors

**Comment by ulfgebhardt** [comment]
Will you open a new PR for it @Oroxzy ?

**Comment by ulfgebhardt** [comment]
closing in favor of https://github.com/vmangos/core/pull/1037

**Pull request closed without merging**
