### PR TITLE
minor refactor of filterLedgeSpans

### PR DESCRIPTION
**Pull request by Gamemechanicwow**
## 🍰 Pullrequest

**filterLedgeSpans:**
Changed variable names in filterLedgeSpans to reflect names in recast.
Removed unnecessary std::lists

**Other minor stuff:**
Changed 0 to AREA_NONE were applicable.
Fixed logic in getGridBounds to calculate correct bounds if there are only liquid verts

### Proof

- None

### Issues

- None

### How2Test

- None

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by icedcolor** [comment]
After this modification, the map extracted by the extractor will lose 0343132.mmtile, resulting in monsters from Stormwind Prison not attacking the player and evading the behavior.

**Comment by Gamemechanicwow** [comment]
> After this modification, the map extracted by the extractor will lose 0343132.mmtile, resulting in monsters from Stormwind Prison not attacking the player and evading the behavior.

I don't believe this PR is the cause of your issue 🤔 

I can't see how this could have any impact on tiles not being generated. The mentioned tile is generated when I try.

**Comment by icedcolor** [comment]
Hello, can you send me the four map generators you generated? Thank you!

**Comment by Gamemechanicwow** [comment]
> Hello, can you send me the four map generators you generated? Thank you!

You can download the newest binaries here https://github.com/vmangos/core/releases

**Comment by w5860363** [comment]
@Gamemechanicwow Confirm that when the extractor is not set to high resolution, mmap is missing 0343132.mmtile

At the same time, the console reported error mmap.not found 0343132.mmtile

**Pull request merged**
