### PR TITLE
Updated database scripts to fix voodoo feathers quest

### LINKED ISSUE #1442: 🐝 [Bug] Missing Quest End Script Voodoo Feathers (8425)
## 🐝 Bug report - Quest
The questgiver should say some text and give you a buff
see: https://classic.wowhead.com/quest=8425/voodoo-feathers#comments

Commit Hash:  1fd3946

### PR DESCRIPTION
**Pull request by scottnice**
## 🍰 Pullrequest

Updated database scripts to fix voodoo feathers quest
After the voodoo feathers quest is completed the fallen hero of the horde will now correctly transform into non-ghost form, cast battleshout, say some text, kneel, stand, and transform back into a ghost with an animation

### Proof

- https://youtu.be/la2GTYLeiak?t=473

### Issues

- fixes #1442

### How2Test

- Turn in quest

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by NickTyrer** [comment]
Looking at the video, you should remove the gossip and questgiver flags at the start of the script and add them at the end.

**Comment by scottnice** [comment]
> Looking at the video, you should remove the gossip and questgiver flags at the start of the script and add them at the end.

Updated

**Comment by ratkosrb** [comment]
Some issues that I fixed in the migration:
- It's best to use the explicit "Add Flags" and "Remove Flags" mode for the "Modify Flags" command. There's a chance things get messed up with the "Toggle" option.
- When you want creature to cast a spell on itself, always add the "Target Self" flag, otherwise it will throw an error if the player who turned in the quest disappears before the script ends.
- The id of quest scripts should match the id of the quest itself, not use arbitrary numbers. The core even warns you about that on startup.

**Comment by scottnice** [comment]
> Some issues that I fixed in the migration:
> 
>     * It's best to use the explicit "Add Flags" and "Remove Flags" mode for the "Modify Flags" command. There's a chance things get messed up with the "Toggle" option.
> 
>     * When you want creature to cast a spell on itself, always add the "Target Self" flag, otherwise it will throw an error if the player who turned in the quest disappears before the script ends.
> 
>     * The id of quest scripts should match the id of the quest itself, not use arbitrary numbers. The core even warns you about that on startup.

@ratkosrb thank you for the info.

**Pull request merged**
