### PR TITLE
Add gameobject blue recluse sign

### LINKED ISSUE #516: Missing sign The Blue Recluse
**Current behavior**: 
The sign is missing outside
asd

**Expected behavior**: 
see 0.23 https://www.youtube.com/watch?v=91kfcn79zXU

**Client version**: 
1.12.1
**Commit hash**: 

**Operating system**: 
Win 10

### PR DESCRIPTION
**Pull request by NickTyrer**
fixes #516

### CODE REVIEW

**Comment by GrenderG** [comment]
image
image2


Lol, the sign is literally overlapping with the lamp post. WTF, Blizz. :rofl:

**Comment by NickTyrer** [comment]
They must have been working on this part of stormind last thing on a friday afternoon before a bank holiday.

**Comment by Kittnz** [comment]
this info isn't from sniffs is it?

**Comment by NickTyrer** [comment]
yes

**Pull request merged**
