### PR TITLE
Spawn The Dark Portal area.

### PR DESCRIPTION
**Pull request by Daribon**
Spawns all the missing NPCs from the Dark Portal area.
WoWScrnShot_100220_185647

### CODE REVIEW

**Comment by ratkosrb** [comment]
What about the packs patrolling the crater?

**Comment by Daribon** [comment]
Just haven't done those yet.

**Comment by ulfgebhardt** [comment]
@Daribon Whats the status of this? Could you obtain the missing data? If not can we merge this partially and could you open an Issue for the missing data? <3

**Comment by Daribon** [comment]
I will update it with waypoints after new years eve.

**Comment by ulfgebhardt** [comment]
@Daribon whats the status on this? <3

**Pull request merged**
