### PR TITLE
Update and add NPC movement scripts - Badlands

### PR DESCRIPTION
**Pull request by NickTyrer**

### CODE REVIEW

**Comment by NickTyrer** [comment]
Currently missing waypoints for Angor Patrol (only partial are available in current sniff).

**Comment by ratkosrb** [comment]
I'll check it out.

**Comment by ulfgebhardt** [comment]
@NickTyrer Could you obtain the missing data? If not, can we merge the complete parts of it and make an issue for the rest including the incomplete data? <3

**Comment by NickTyrer** [comment]
@ratkosrb no need to sniff this, cmangos has just added lots of movement data to this zone, I will use that.

**Pull request merged**
