### PR TITLE
Removed non-vanilla auth codes

### PR DESCRIPTION
**Pull request by ghost**
Removed non-vanilla auth codes:
- There was no Battle.net accounts support (only WoW ones) before 3.3.5 patch in WoW
- There was no 10-day free trial before some TBC patch

### CODE REVIEW

**Comment by Daribon** [comment]
Should remove all those commented lines at the bottom as well, they all appear to be from a later version.

WOW_FAIL_TRIAL_ENDED should be removed as well, trial wasn't added until TBC.
Even found the old european page for it, which still appears to be up: http://media.wow-europe.com/bctrial/splash_en.html

WOW_FAIL_LOCKED_ENFORCED is most likely from another expansion too, I've been unable to find it anywhere on old emulators.

**Comment by ghost** [comment]
> Should remove all those commented lines at the bottom as well, they all appear to be from a later version.
> 
> WOW_FAIL_TRIAL_ENDED should be removed as well, trial wasn't added until TBC.
> Even found the old european page for it, which still appears to be up: http://media.wow-europe.com/bctrial/splash_en.html
> 
> WOW_FAIL_LOCKED_ENFORCED is most likely from another expansion too, I've been unable to find it anywhere on old emulators.

Try to send WOW_FAIL_LOCKED_ENFORCED to client. If it won't work, I will remove it. TrinityCore also [defines](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/authserver/Authentication/AuthCodes.h) some of commented opcodes.

Are you sure anti-indulgence system was not in vanilla WoW? IIRC, it is mandatory in China and WoW was already released here.

**Comment by ghost** [comment]
What is WOW_FAIL_OVERMIND_CONVERTED? Is it about Battle.net account conversion?

**Comment by Daribon** [comment]
Some WoTLK code for sure.

**Comment by ghost** [comment]
I have removed these opcodes. I'm not sure about anti-indulgence.

I have tested all opcodes on 1.6.1 and 1.12 clients, so this pull request is now ready.

**Comment by ratkosrb** [comment]
The login server is meant to support multiple versions. so removing definitions for newer versions does not make sense.

**Comment by GrenderG** [comment]
But this project should only support up to 1.12.3, no?

**Comment by ratkosrb** [comment]
The realmd is multi expansion and can be used with other cores.

**Comment by GrenderG** [comment]
I know, but I don't see any reason to support post Vanilla in vMaNGOS' realmd.

**Comment by ratkosrb** [comment]
It already supports it. Why remove useful functionality that already exists? It allows you to run servers for multiple expansion on the same realmlist. You could have vmangos vanilla + cmangos tbc + trinitycore wotlk all running with same account database.

**Comment by GrenderG** [comment]
I got your point now. Makes sense. :+1:

**Pull request closed without merging**
