### PR TITLE
Add support for Drone CI and update Travis CI

### PR DESCRIPTION
**Pull request by tonymmm1**
Adds support for Drone CI automated builds, file has 2 pipelines configure for amd64 and arm64 respectively.

### CODE REVIEW

**Comment by ratkosrb** [comment]
Do I have to go enable this somewhere? For Travis I think I had to go sign up on their website?

**Comment by tonymmm1** [comment]
This file allows either use of self-hosted or https://cloud.drone.io/ which is hosted by developers of Drone CI.

**Comment by tonymmm1** [comment]
I just thought it would be convenient for people forking and or mirroring to have another CI option.

**Comment by tonymmm1** [comment]
Also the arm64 pipeline is optional and can be removed or commented out.

**Comment by ratkosrb** [comment]
To be honest the arm64 option is the more useful one, because amd64 linux builds already get tested on Travis. If you know how to get some MSVC and Clang based CI working that would be great too.

**Comment by tonymmm1** [comment]
Do you want clang and gcc as separate pipelines, I will look into it and get back to you. I am not as familiar with compiling for Windows so that is not a guarantee.

**Comment by ratkosrb** [comment]
Ideally we would have simultaneous builds running for GCC, Clang, and MSVC after every commit. At cmangos they already have automated Windows builds working, but I don't know how to set this up. Do you know if its possible to get those 2 working with Travis? They use AppVeyor at cmangos.

Untitled

https://ci.appveyor.com/project/cmangos/mangos-classic/build/0.18.1317

**Comment by tonymmm1** [comment]
I just added Clang pipeline will finish with MSVC on Drone and then look at Travis.

**Comment by tonymmm1** [comment]
I will look into this for now https://github.com/mstorsjo/msvc-wine.

**Comment by tonymmm1** [comment]
I think this new Travis file should work for parallel builds of gcc and clang.

**Comment by tonymmm1** [comment]
I don't quite know how to use MSVC on Linux without some weird hacks like Wine or on a native Windows appliance.

**Comment by ratkosrb** [comment]
The MSVC build ought to be on Windows.

**Comment by tonymmm1** [comment]
Yeah CI environment is pretty much Linux only unless there is a tool chain I do not know about and or Travis has a work around. Sorry.

**Comment by tonymmm1** [comment]
@ratkosrb I will test out the travis file and see if it works on my branch.

**Comment by tonymmm1** [comment]
@ratkosrb Ok build is running on two simultaneous compiles so it should be ready to go.
image

**Comment by tonymmm1** [comment]
Ok now I am looking https://docs.travis-ci.com/user/reference/windows/ will try to get a Windows build going as well.

**Comment by tonymmm1** [comment]
I am leaving it alone for now in working order as Travis direct Windows compile seems to be in beta and I am unable to get ACE libraries compiled for Windows. In the future I might create a custom Chocolatey library for ACE and then just have the Travis pull that.

**Pull request merged**
