### PR TITLE
Fix reputation requirement for Harpy Hide Quiver

### LINKED ISSUE #232: Harpy Hide Quiver should require Revered reputation to get it
**Current behavior**: 
You can buy the "Harpy Hide Quiver" with no reputation.

**Expected behavior**: 
"Harpy Hide Quiver" should require Revered reputation to get it (https://classic.wowhead.com/item=19319/harpy-hide-quiver#comments:id=2634652), the same way as the "Gnoll Skin Bandolier" is requiring it now.

**Steps to reproduce**:

1. Visit any Frostwolf / Stormpike vendor and try to buy the Quiver with no reputation.

Fix:

```sql
update item_template set required_reputation_rank = 6 where entry = 19319;
```

### PR DESCRIPTION
**Pull request by NickTyrer**
fixes #232 
proof
ddddd

### CODE REVIEW

**Comment by ratkosrb** [comment]
Counter-proof.

Untitled

https://wow.tools/dbc/?dbc=itemsparse&build=1.13.5.34138#page=1&search=19319

There is no reputation requirement assigned to the item template in ItemSparse.db2 which contains all item data.

**Comment by NickTyrer** [comment]
"**test**.classic_itemsparse", the screenshot is from a live classic server.

**Comment by ratkosrb** [comment]
test.classic_itemsparse is just ItemSparse.db2 converted to a sql table, if you don't believe me, then write your own reader for ItemSparse.db2 and check out the data for entry 19319. There is no faction requirement on the item template. All data for 1.12 in vmangos matches db2 data from Classic client.

**Comment by GrenderG** [comment]
I know it's confusing @ratkosrb, but the truth is that:

1. All wowhead comments from 1.5.1 up to 1.12.1 explicitly say that you require Revered reputation to get it.
2. **At this moment, in Classic, the NPC is only selling the item if you are Revered.**

More proof:

- [WoWWiki](https://wowwiki.fandom.com/wiki/Harpy_Hide_Quiver?oldid=138232) 
- [Allakhazam](http://web.archive.org/web/20060524160537/http://wow.allakhazam.com/db/item.html?witem=19319) 
- [One of the several wowhead comments](https://classic.wowhead.com/item=19319/harpy-hide-quiver#comments:id=4186)

**Comment by NickTyrer** [comment]
@GrenderG, sorted now, I need to modify the PR to assign a condition to the vendor rather than the item_template.

**Comment by ratkosrb** [comment]
@GrenderG You are confusing an on-use requirement on the item itself, with a vendor requirement.

Here is an item that has a requirement on the template. You cannot learn this recipe if your reputation is below Friendly.
https://classic.wowhead.com/item=13484/recipe-transmute-earth-to-water

Notice how it shows the requirement on the item tooltip.

Now here is the Harpy Hide Quiver.
https://classic.wowhead.com/item=19319/harpy-hide-quiver

Do you see a requirement on the tooltip? No, because there is no on-use reputation requirement. Go ahead and click the Links button and link it in game, and you'll see it shows no requirement there either.

All our item data for 1.12 is synced with Classic, it is 100% correct, and nobody should change anything in `item_template`, unless its progression related.

**Comment by GrenderG** [comment]
Yeah you are totally right, @ratkosrb, sorry for the misunderstanding; the requirement should be placed on the vendor itself as @NickTyrer pointed out.

**Comment by NickTyrer** [comment]
@brotalnia `SELECT * FROM npc_vendor WHERE entry = 13217` shows that no condition is assigned to any item he sells. It looks like all the `item_template` entries have `required_reputation_rank = 6` on all the items. Am I right in assuming the `required_reputation_rank` will need to be set to 0 and conditions added for all items. (note: this may be a wider issue in the database).

**Comment by ratkosrb** [comment]
@NickTyrer You should not change `item_template` at all! Data for it comes from db2 files in client. Just assign a reputation condition to Harpy Hide Quiver in `npc_vendor` and that's it.

**Comment by NickTyrer** [comment]
@ratkosrb sorry if i'm not getting this but based on what you said yesterday, for example https://classic.wowhead.com/item=19321/the-immovable-object which has required_reputation_rank = 6 currently set should show rep on tooltip in wowhead?

**Comment by ratkosrb** [comment]
Hmm, you are right, it seems I have neglected to correct required_reputation_rank for some items, probably cause we didn't have conditions for vendors back when I did that. I'll write a tool to move those requirements to vendor.

**Pull request closed without merging**
