### PR TITLE
[WIP] Midsummer event

### PR DESCRIPTION
**Pull request by GrenderG**
This event is unfinished / using TBC stuff, now that the event is near on Classic servers, would be nice to finish implementing it. 

For reference: https://wowwiki.fandom.com/wiki/Midsummer_Fire_Festival?oldid=382277

### CODE REVIEW

**Comment by Kittnz** [comment]
I agree, ill sniff everything on classic so we have correct positions etc

**Comment by Daribon** [comment]
Midsummer event is now live on classic.

**Comment by NickTyrer** [comment]
Flame of westfall is missing in vmangos 
asdsd

**Comment by GrenderG** [comment]
~~The scale I'm using for 17066 is a placeholder, by the way. It was 0 before, making the NPC fall through the pole.~~

**Comment by Daribon** [comment]
Oh yeah, this event looks to be a complete mess currently on vmangos.
The fireplace at ironforge looks to be complete guess spawned or it was downported from a expansion where the event was vastly different.
Vmangos
WoW_XmrLEqCAsf
Classic 1.13.4:
WowClassic_QD1t80OUVc

**Comment by GrenderG** [comment]
I'm pretty sure it's downported from TBC, also I think campfire gobjects aren't the correct ones.

**Comment by Kittnz** [comment]
I think i got most of it now, i still need to do the dungeons, but the rest should be good

**Comment by NickTyrer** [comment]
The gameobject from the fire festival is in stormwind
asdas

**Comment by ulfgebhardt** [comment]
@GrenderG Whats the status on this? Can we get this merged? Whats missing? <3

**Comment by Kittnz** [comment]
We better remove existing spawns and import them from sniffs

**Comment by ulfgebhardt** [comment]
@GrenderG This is the oldest PR now - lets have it finished? <3

**Comment by GrenderG** [comment]
I lack the data to finish it. Maybe @Kittnz can help.

**Comment by Kittnz** [comment]
Poke me on discord

**Comment by Oroxzy** [comment]
all spawns from kittnz sniffs :)
If i missed something just tell me the entry and i will redo the spawn list

https://gist.github.com/Oroxzy/591ecb408f823da2496df444ed8b13a6

**Comment by Oroxzy** [comment]
Got the Burning Blossom (torch throwing thing) working now!

Gist file updated

we have now 18/26 camps, these are missing:

181339 Flame of Silithus
181340 Flame of Winterspring
181342 Flame of Azshara
181343 Flame of Un'Goro
181346 Flame of Dire Maul
181347 Flame of Blackrock Spire
181348 Flame of Stratholme
181349 Flame of the Scholomance

maybe we take them from the old event or just wait 2 months for fresh sniffs.

Also some old comments from [wowhead](https://classic.wowhead.com/item=23247/burning-blossom)

> Yes, when you throw this into a bonfire it gives you a 60 minute buff which increases your critical strike and spell critical strike chance by 3%, but only to the person who threw it. Additional blossoms (2 or 3 total within an unknown time limit) give the buff to everyone near the bonfire. The additional blossoms don't have to come from the same person.
> 
> The fire resistance buff (+30 for 1 hour) comes from the 'maypole'. There must be at least 2 people connected to the pole for it to work.
> 
> The stamina buff (+30 stamina for 1 hour) comes from someone turning in a 'Flame of [city]' stolen from

> the pole must have 2 players of the same faction, does not work cross faction at all.

> Throwing this into a bonfire gives you a 60 minute buff which increases your critical strike- and spell critical strike chance by 3%.
> 
> According to my scrolling combat text I also got healed for +10000 hp.

**Comment by GrenderG** [comment]
Closing this in favor of https://github.com/vmangos/core/pull/1250.

**Pull request closed without merging**
