### PR TITLE
Add command to mount any targeted creature.

### PR DESCRIPTION
**Pull request by ghost**
* For GMs. Don't need a spell or an item, just hop onto something and ride off into the sunset.

### CODE REVIEW

**Comment by coolzoom** [comment]
@shenna 
having fun with it but im having issue with it as well
1, level a troll character
2, select a pig/boar
3, input mount, then you will become a pig:D



image

**Comment by coolzoom** [comment]
same as the scorpion :D
image

**Comment by coolzoom** [comment]
it may not issue at all becuase they may dont have mounting point. still have a lot fun.

**Comment by ghost** [comment]
Yeah, if model doesn't have mounting points you'll just morph into it. Some humanoids will have you sitting on their right arm for some reason.

**Pull request merged**
