### PR TITLE
Implement SPELL_ATTR_EX_DONT_REFRESH_DURATION_ON_RECAST

### PR DESCRIPTION
**Pull request by schell244**
## 🍰 Pullrequest
- implement SPELL_ATTR_EX_DONT_REFRESH_DURATION_ON_RECAST like CMangos

### Proof
https://github.com/cmangos/mangos-classic/blob/bb48d3144b3c603d307b3eada4ad893765422d24/src/game/Spells/SpellDefines.h#L25

### Issues
- None

### How2Test
- None

### Todo / Checklist
- [X] None

### CODE REVIEW

**Comment by ratkosrb** [comment]
We have the names of all spell attributes from the db2 file from 2.5.1, but there's no point in renaming without implementing. It would only make it confusing why they don't do anything. Right now its easy to tell which ones aren't implemented cause they are not in the enum. So only rename attributes if you are implementing them.

**Comment by ghost** [comment]
This PR is incorrect, SpellAttrEx 0x00000800 should be in fact Unique Aura.
Such auras cannot stack (or occupy multiple slots) on a target, despite having different casters.

https://classic.wowhead.com/spell=16468/mothers-milk
https://wow.tools/dbc/?dbc=enumeratedstring&build=2.5.1.38093#page=6

**Comment by schell244** [comment]
Thanks for verifying this. I'll close this PR for now. Just for documentation, this was the commit of CMangos:
https://github.com/cmangos/mangos-classic/commit/55a5158cab892f3e6e677c4ae32f2afa16b060db

**Comment by ghost** [comment]
Probably @killerwife wants to reinvestigate this :innocent:

**Comment by killerwife** [comment]
Yeah, I know I am full of shit :D Spell attributes are on the menu this month from enumerated strings.

**Pull request closed without merging**
