### PR TITLE
german script text locales - silverpine forest quests

### PR DESCRIPTION
**Pull request by schell244**
- Escorting Erland, source: https://www.youtube.com/watch?v=HOSYHXg3pdc
- Pyrewood Ambush, source: https://www.youtube.com/watch?v=LG9hExSKYLI

### CODE REVIEW

**Comment by ratkosrb** [comment]
That is not what 'sniff' means.

**Comment by schell244** [comment]
Would source be better?

**Comment by ratkosrb** [comment]
We should just update the script to use broadcast text ids instead of this custom table.

**Comment by schell244** [comment]
I didn't expect broadcast texts to contain these script texts. I'll try to find the matching ids and update this PR. Thank you.

**Comment by ratkosrb** [comment]
Broadcast texts contain all script texts. The script is old and that's why it uses the `script_texts` table instead of `broadcast_text`.

**Comment by schell244** [comment]
I found all matching broadcast_text strings:

script_texts = broadcast_text ID

Quest: Escorting Erland
-1000306 = 481
-1000307 = 482
-1000308 = 543
-1000309 = 544
-1000310 = 541
-1000311 = 483
-1000312 = 484
-1000314 = 535
-1000315 = 536
-1000316 = 537
-1000317 = 539
-1000318 = 538
-1000313 = 534

Quest: Pyrewood Ambush:
-1000553 = 542
-1000554 = 545

**Pull request closed without merging**
