### PR TITLE
Add Firecrackers Script

### PR DESCRIPTION
**Pull request by NickTyrer**
## 🍰 Pullrequest
This PR will set off random firecrackers during the lunar festival event

### How2Test
.event start 7

### Todo / Checklist
FIx errors

### CODE REVIEW

**Comment by NickTyrer** [comment]
I think this functionality should be handled by the core as the radius used in generic scripts is not large enough to cover an entire city.

**Comment by ratkosrb** [comment]
Just assign the script to a NPC near the gameobjects?

**Comment by NickTyrer** [comment]
The gameobjects are everywhere, you would have to assign it to many npc's throughout the world.

**Comment by Kittnz** [comment]
This isn't how it works. The firecrackers at random do the despawn animation when they despawn. And when they respawn it will spawn one of the 2 different firecracker gobs.

**Comment by NickTyrer** [comment]
I dont think that functionality is possible, unless you know a way?

**Comment by Oroxzy** [comment]
similar to this?
https://github.com/vmangos/core/blob/development/src/scripts/world/fireworks_show.cpp

**Comment by Kittnz** [comment]
No, different @Oroxzy .
@NickTyrer  You can do it with pools, i think it's the only way to do it. @brotalnia WYT?

**Comment by ratkosrb** [comment]
I guess you'll need a c++ script assigned to those gameobject entries to despawn them. And for each spawn point you need a pool of all the different entries that can spawn there.

**Comment by Kittnz** [comment]
Wouldn't it be easier to just add a event script to it? make it despawn every x seconds ?

**Comment by NickTyrer** [comment]
I can add the pooling but I wont be able to do the c++

**Comment by NickTyrer** [comment]
I have now added the relevant pools.

**Pull request merged**
