### PR TITLE
Implement changes to MC attunement.

### PR DESCRIPTION
**Pull request by Daribon**
What is yet to be implemented:

- There should be the following gossip text when interacting with Unstable Rift Crystal:

`('You see large cavernous tunnels and corridors reflected inside the crystal. You recognize the area as the Molten Core.', '', 10899, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),`

- Gossip option text for Unstable Rift Crystal, should teleport on click:

`('<Touch the unstable rift crystal.>', '<Touch the unstable rift crystal.>', 10900, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),`

- Teleport function on Unstable Rift Crystal for quest 7848

- Allow teleport jump when completing quest 7487.

- Lothos Riftwaker should have no teleport function pre patch 1.11.0

- Change quest text for 7848 after 1.7 when Unstable Rift Crystal is implemented.

- Unstable Rift Crystal might have incorrect size atm, it is unknown what size it should be.

- According to two comments from Allakhazam between 1.3 to 1.5 Dwarves were auto attuned to Molten core, without doing the quest. Patch 1.5.0 patch notes confirms this, however only mentions Dwarf Priest being able to pick up the attunement quest: "Dwarven Priests may now undertake the Molten Core discovery quest; "Attunement to the Core." So I'm not sure if it was only dwarf priest or all dwarf classes that were auto attuned until patch 1.5.

Source for Unstable Rift Crystal position is wowd-db
Source for 1.3 - 1.4 quest text is Nexus Serv, french wowemu DB.
Source for 1.4 - 1.7 quest text is from the following images:
5_years_wow_raid_molten_core_2005_003
5_years_wow_raid_molten_core_2005_001
5_years_wow_raid_molten_core_2005_002

### CODE REVIEW

**Comment by GrenderG** [comment]
Do you know what's the meaning of this sentence? (Patch 1.4 Notes):

> The Molten Core discovery quest has had its objective moved from inside the Molten Core to Blackrock Depths. 

I guess the quest was just to enable the teleport, there was no attunement, since to complete it you needed to literally enter MC.

**Comment by Daribon** [comment]
> 
> 
> Do you know what's the meaning of this sentence? (Patch 1.4 Notes):
> 
> > The Molten Core discovery quest has had its objective moved from inside the Molten Core to Blackrock Depths.
> 
> I guess the quest was just to enable the teleport, there was no attunement, since to complete it you needed to literally enter MC.

Before patch 1.4.0, Core Fragment spawned inside MC. After patch 1.4.0, it was moved to the MC portal in BRD. 

So in order to get attuned to MC before patch 1.4.0, you would have to enter MC itself.

**Comment by GrenderG** [comment]
Oh, true, there's no need for attunement if you enter MC through BRD, completely forgot about that. :joy:

**Comment by ratkosrb** [comment]
> 
> 
> Do you know what's the meaning of this sentence? (Patch 1.4 Notes):
> 
> > The Molten Core discovery quest has had its objective moved from inside the Molten Core to Blackrock Depths.
> 
> I guess the quest was just to enable the teleport, there was no attunement, since to complete it you needed to literally enter MC.

This is already implemented, although the rock spawn inside MC is a complete guess.

**Pull request merged**
