### PR TITLE
fixed some german broadcast locales

### LINKED ISSUE #1046: 🐛 [Bug] broadcast text locales - some (format?) issues for german texts
## 🐛 Bug report
I noticed some spelling issues within some german texts.
Looks like "D. $n" was used as replace.

broadcast text errors

### Expected behavior
Texts should not be cut.

### Steps to reproduce
1. open db
2. run query: 
``` sql 
SELECT entry,male_text_loc3 FROM locales_broadcast_text WHERE male_text_loc3 LIKE '%D. $n%'; 
```

Commit Hash:  
9dba4cc

### PR DESCRIPTION
**Pull request by schell244**
## 🍰 Pullrequest
Corrected some spelling/format issues within german broadcast locales.

### Proof
- None 

### Issues
- fixes https://github.com/vmangos/core/issues/1046

### Todo / Checklist
- [X] None

### CODE REVIEW

**Comment by ratkosrb** [comment]
Correcting broadcast texts? But that data is all sniffed.

**Comment by schell244** [comment]
I've noticed some of those spelling issues a while ago, yesterday I checked these texts on trinity core.
It seemd than they had the same issues, like one or two texts also contained this "D." but they have corrected most of them.
So when when those texts are broadcasted, it basically looks like this:

"Hilfe! D. Scheckiger Worg greift uns an!"
"Help! D. Mottled Worg is attacking us!" 

gamebreaking of course.... 

quest: https://classic.wowhead.com/quest=435/escorting-erland
text:   1074
$n:     https://classic.wowhead.com/npc=1766/mottled-worg

**Comment by ratkosrb** [comment]
You need to provide some proof the sub string "D." gets removed in classic servers. Otherwise we should not touch sniffed data. The goal is to emulate what Blizzard does, and that does not include fixing their spelling mistakes.

**Comment by schell244** [comment]
So I found a video where someone was doing the quest Escorting Erland where I saw the bug on vmangos.
Sadly a different aggro text was broadcasted in the video (I think there are 3 radom texts or so) which did not contain a "D." substring. 
But at 3:05, the video showes a text which contained a cut text part:
https://www.youtube.com/watch?v=HOSYHXg3pdc 
escorting erland 2

The " Ei. " part is exactly the same in vmangos broadcast text. 

So Blizzard definately seem to broadcast some cut/broken text elements - which makes this PR a custom patch.

**Pull request closed without merging**
