### PR TITLE
Fix Starshards and Curse of Agony

### PR DESCRIPTION
**Pull request by WobLight**
- tick damage ramp should not affect spell power increment
- fractional part is dithered locally as presently there's no dithering on damage

I'm planning to use that dithering function to fix rounding in spell damage/heal calculation everywhere so review carefully.

### CODE REVIEW

**Comment by WobLight** [comment]
Anyone who can re-run CI?

**Comment by WobLight** [comment]
mm I'll try merge with dev

**Comment by ratkosrb** [comment]
The CI seems to be bugged atm, it fails on development branch too.

**Comment by WobLight** [comment]
I have a big dithering pr ready, but this should get merged first

**Pull request merged**
