### PR TITLE
(Q823) Report to Orgnil should require prerequisite quest (Q805) Report to Sen'jin Village

### PR DESCRIPTION
**Pull request by FlagFlayer**
## 🍰 Pullrequest
As per title, this pull requests gives Q823 Report to Orgnil the prerequisite requirement to complete Q794 Burning Blade Medallion.

### Proof

- [Wowpedia article dating 11 June 2006](https://wowpedia.fandom.com/wiki/Report_to_Orgnil?oldid=160801)
- [Source code for above article (the template used to display the quests no longer functions)](https://wowpedia.fandom.com/wiki/Report_to_Orgnil?action=edit&oldid=160801)

### Issues

- None

### How2Test

- Get to level 4
- Have the quest Report to Orgnil (Q823) not be available
- Complete Burning Blade Medallion (Q794)
-  Report to Orgnil (Q823) should now be available

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by ratkosrb** [comment]
Have you verified this is the case on classic?

**Comment by FlagFlayer** [comment]
In spite of evidence from 2006 indicating that it was a chain, it seems to not be a chain in Classic: https://youtu.be/Vd8QeFP1YN8?t=56

Should this be closed then?

**Comment by GrenderG** [comment]
> In spite of evidence from 2006 indicating that it was a chain, it seems to not be a chain in Classic: https://youtu.be/Vd8QeFP1YN8?t=56
> 
> Should this be closed then?

That video is not from Classic, it's from a Vanilla emulator.

**Comment by ratkosrb** [comment]
Go test on the official classic servers. The video you linked is from a private server like @GrenderG said.

**Comment by FlagFlayer** [comment]
I cancelled my classic subscription a while back. I'm not going to pay anything to blizzard just to test a bug.

**Comment by GrenderG** [comment]
> I cancelled my classic subscription a while back. I'm not going to pay anything to blizzard just to test a bug.

PTR is free, not sure if it's currently active though.

**Comment by NickTyrer** [comment]
PTR is still active! Report to Orgnil does not require Report to Sen'jin Village on there.

**Comment by ratkosrb** [comment]
Thank you @NickTyrer for bothering to test. This pull request is wrong then.

**Comment by FlagFlayer** [comment]
I'm still quite certain this is a mistake on Classic, considering the quest text:
Report to Orgnil: "We at Sen'jin Village are not without our own troubles, and we thank you for your aid. **But the news you bring regarding the Burning Blade could be trouble for everyone.**"

Report to Sen'jin Village: "**Tell Gadrin of the Burning Blade,** and that they have reached the Valley of Trials. Discover from him if they have yet reached Sen'jin."

The text of Report to Orgnil REALLY doesn't make sense independently, meanwhile there is also evidence dating to 2006 that Report to Sen'jin Village was indeed a prequest. I highly doubt that Classic implemented this quest correctly.

**Comment by FlagFlayer** [comment]
Regardless, if you think we should base this off of Classic then I guess we're done here.

**Comment by FlagFlayer** [comment]
@ratkosrb @NickTyrer Mentioning you guys since I'm unsure whether you'd be notified on a closed pull request. Let me know if the above reasoning is valid, or should I lay this to rest since Classic is the template we're basing everything on and trying to emulate.

**Comment by GrenderG** [comment]
Weird indeed, Allakhazam from 2004 also says that Report to Sen'jin Village is a requisite. https://web.archive.org/web/20041121223651/http://wow.allakhazam.com/db/quest.html?wquest=823 (and https://web.archive.org/web/20041121221206/http://wow.allakhazam.com/db/quest.html?wquest=805 says that it leads to 823).

**Comment by NickTyrer** [comment]
I dont like treating classic data as a panacea either and I think I would rather trust Allakhazam. Just my opinion.

**Comment by NickTyrer** [comment]
On the other hand, It does seem like a wierd issue for Blizz to mess up when translating vanilla to classic.

**Comment by GrenderG** [comment]
image
I founds this comment on Allakhazam from 2007 during TBC. https://web.archive.org/web/20071225144243/http://wow.allakhazam.com/db/quest.html?wquest=823

I wonder if it was changed somewhere between Vanilla and TBC, or if it has always been like this and Allakhazam had it listed as pre requisite instead of part of a quest chain (and wowpedia copied it from Allakhazam).

> On the other hand, It does seem like a wierd issue for Blizz to mess up when translating vanilla to classic.

I agree on this though.

**Comment by NickTyrer** [comment]
I tested with a troll on the PTR.

**Comment by FlagFlayer** [comment]
But then again, considering the quest text, Report to Orgnil is utter nonsense without the context from Report to Sen'jin Village

**Comment by ratkosrb** [comment]
Whether it makes sense or not is irrelevant, only evidence matters. There are many things in vanilla that don't make sense, the point of the project is to recreate things as they were, not as it would make sense for them to be. And the evidence from classic, which is based on the 1.12.0 data, is that it does not require that quest to be done first. The only way to disprove it is either a video from original vanilla, uploaded in 2004-2006, in which the player does not see Report to Orgnil before he does Report to Sen'jin Village, or a blue post from Blizzard saying they changed the requirement for this quest in Classic, like they announce all other changes they do.

**Comment by FlagFlayer** [comment]
Comments on https://classicdb.ch/?quest=806 seem pretty unanimous about the only prequest to Dark Storms being Report to Orgnil. We are done here.

**Pull request closed without merging**
