### PR TITLE
Add new table "instance_player_immunity"

### PR DESCRIPTION
**Pull request by ghost**
## 🍰 Pullrequest
The new table "instance_player_immunity" can be used to apply immunities to the players for each map. Structure of the table:

| Field          | Type             | Null | Key |
|----------------|------------------|------|-----|
| map_id         | int(10) unsigned | NO   | PRI |
| immunity_flags | int(10) unsigned | NO   |     |
| enabled        | tinyint(1)       | NO   |     |
| comment        | varchar(256)     | NO   |     |

The immunities are specified as bitmask in column "immunity_flags":

```
PLAYER_IMMUNITY_CHARM          = 0x00000001,
PLAYER_IMMUNITY_FEAR           = 0x00000002,
PLAYER_IMMUNITY_SILENCE        = 0x00000004,
PLAYER_IMMUNITY_SLEEP          = 0x00000008,
PLAYER_IMMUNITY_STUN           = 0x00000010,
PLAYER_IMMUNITY_FREEZE         = 0x00000020,
PLAYER_IMMUNITY_KNOCKOUT       = 0x00000040,
PLAYER_IMMUNITY_POLYMORPH      = 0x00000080,
PLAYER_IMMUNITY_HORROR         = 0x00000100,
PLAYER_IMMUNITY_DAZE           = 0x00000200,
PLAYER_IMMUNITY_SAPPED         = 0x00000400,
PLAYER_IMMUNITY_KNOCK_BACK     = 0x00000800,
PLAYER_IMMUNITY_POWER_DRAIN    = 0x00001000,
```

In order to not interfere with scripts (source spell ID 0) or custom spells I chose very high spell IDs to identify the source of the immunities for removal:

```
SPELL_SRC_IMMUNITY_CHARM       = 0xFFFF0000,
SPELL_SRC_IMMUNITY_FEAR        = 0xFFFF0001,
SPELL_SRC_IMMUNITY_SILENCE     = 0xFFFF0002,
SPELL_SRC_IMMUNITY_SLEEP       = 0xFFFF0003,
SPELL_SRC_IMMUNITY_STUN        = 0xFFFF0004,
SPELL_SRC_IMMUNITY_FREEZE      = 0xFFFF0005,
SPELL_SRC_IMMUNITY_KNOCKOUT    = 0xFFFF0006,
SPELL_SRC_IMMUNITY_POLYMORPH   = 0xFFFF0007,
SPELL_SRC_IMMUNITY_HORROR      = 0xFFFF0008,
SPELL_SRC_IMMUNITY_DAZE        = 0xFFFF0009,
SPELL_SRC_IMMUNITY_SAPPED      = 0xFFFF000A,
SPELL_SRC_IMMUNITY_KNOCK_BACK  = 0xFFFF000B,
SPELL_SRC_IMMUNITY_POWER_DRAIN = 0xFFFF000C,
```

The table "instance_player_immunity" is initially empty. I used the implementation of "AuraRemovalMgr" as reference.

### Proof
- None

### Issues
- None

### How2Test
Apply this SQL script to the world DB:

```sql
DELETE FROM `instance_player_immunity` WHERE `map_id` = 43;
INSERT INTO `instance_player_immunity` (`map_id`, `immunity_flags`, `enabled`, `comment`)
VALUES
(43, 8, 1, 'Sleep immunity in Wailing Caverns');
```

Enter the Wailing Caverns. The Druids of the Fang will not be able to put the player to sleep anymore.

### Todo / Checklist
- [X] None

### CODE REVIEW

**Comment by ratkosrb** [comment]
You can open pull requests with custom features like this and they can stay open to be visible for users, but I don't plan on merging purely custom functionality that has no blizzlike use case into the project.

**Comment by ghost** [comment]
There's already several other custom stuff which also has no blizzlike use case, e.g. the table "instance_buff_removal" this PR is based on or config parameters like "Rate.Creature.Elite.Elite.Damage". But that's fine, if it is not needed, I'll close the PR. Don't intend to keep it open just to sync it forever with the main branch.

**Comment by ratkosrb** [comment]
@Stoabrogga That was added during the Light's Hope times, I had no authority to prevent it. But I could remove it now.

**Comment by ghost** [comment]
@ratkosrb In my opinion it does not hurt to have a bit of customization, especially if it is non-intrusive. But ok, your project, your rules. I'll use a fork and add this stuff.

**Comment by GrenderG** [comment]
If the project merged all custom stuff from everyone it would be a complete mess. Just leave the PR open as @ratkosrb suggested in case someone else wants to use your changes. You don't even need to keep it synced.

**Comment by ghost** [comment]
Ok, understood. But I cannot reopen the PR, sorry. I deleted the branches and the fork because normally I try to avoid GitHub wherever possible. Should I create a new PR? Perhaps a label (e.g. "custom feature") would be great to mark PRs which are never going to be merged.

**Comment by codestothestars** [comment]
Honestly closing seems fine to me. People can still link to and search for them, and they don't permanently keep the PR count up.

**Pull request closed without merging**
