### PR TITLE
Update Quest Chain 1070

### PR DESCRIPTION
**Pull request by NickTyrer**
## 🍰 Pullrequest
This PR syncs the quest chain with wowhead

<pre>     
    1070
      |
    1085
      |
    1071
      |	
1072  +  1075
  |       |
1073     1076
  |       |
1074  +  1077
      |
1079  +  1080  ---  Problem occurs here completing 1074 and 1077 should open 1079 AND 1080
      |
    1091
      |
 1083 + 1084
      |
     1082
      |
     1081 
</pre>

### CODE REVIEW

**Comment by ratkosrb** [comment]
So did you get it working, or is there still a problem?

**Comment by NickTyrer** [comment]
@ratkosrb still bugged. The chain is all working now except for the issues mentioned above.

**Comment by ratkosrb** [comment]
Utilize a condition at the problem spot. There is a RequiredCondition field in the table. Use that instead of the normal relation fields.

**Comment by NickTyrer** [comment]
This is now working correctly

**Comment by NickTyrer** [comment]
TODO: check if vmangos has this implemented https://github.com/cmangos/classic-db/commit/d8df9dc490711f622dd9447f6ba83d58f6048314

**Comment by ratkosrb** [comment]
Those two quests are scripted, you can test them in game if you wish.

**Pull request merged**
