### PR TITLE
Remove trial opcodes

### PR DESCRIPTION
**Pull request by ghost**
It looks like trial accounts were added in TBC

### CODE REVIEW

**Comment by ratkosrb** [comment]
Please verify your changes are correct before making pull requests. I just checked and both error messages exist in the 1.12 client.

**Comment by ghost** [comment]
@ratkosrb that's weird as trial accounts do not exist in vanilla. Or do they? At least, trial auth code doesn't work.

**Comment by GrenderG** [comment]
They existed.

**Comment by Gamemechanicwow** [comment]
image

iirc.. at some point there was also 10 days trial giftcodes with physical bought gamecards.

**Comment by Daribon** [comment]
Aha, didn't realize

**Comment by ghost** [comment]
In which version were these opcodes added?

**Pull request closed without merging**
