### PR TITLE
Core/Crypto: Update OpenSSL (support 1.1.1 and 3.x.x)

### PR DESCRIPTION
**Pull request by ReyDonovan**
## 🍰 Pullrequest

Update OpenSSL
Support 1.1.1 and 3.x.x
Remove 1.0.1 version
Need test build *Unix System and play on game

### Proof

- None

### Issues

- [X] None

### CODE REVIEW

**Comment by shudza** [comment]
Headers are replaced in windows/dep/include/openssl. Will these headers support both 1.x and 3.x versions?

**Comment by ReyDonovan** [comment]
@shudza I'll rework the PR to support 1.0.1 for Windows and 3.x.x for Unix, Windows doesn't interest me and I updated everything to fit my Win10 and Debian 12 libraries

**Comment by ghost** [comment]
Not working on Ubuntu 22.04

**Comment by ReyDonovan** [comment]
@Nolin7777 this is not possible, the build of Debian 12 and Ubuntu 22.04 is the same
just for fun, I'll even check Ubuntu this evening
Новый точечный рисунок

**Comment by shudza** [comment]
> Not working on Ubuntu 22.04

Can you share more details?

**Comment by ReyDonovan** [comment]
@shudza Debian 12 version OpenSSL 3.0.2 and Ubuntu OpenSSL version 3.0.2, there shouldn't be any problems at all

**Pull request closed without merging**
