### PR TITLE
Fix fishing loot tables in Tirisfal

### PR DESCRIPTION
**Pull request by schell244**
fix for issue https://github.com/vmangos/core/issues/342

I think it would be nice to rename the table "entry" to "area_id" in fishing_loot_template, to not be confused with zone id.

### CODE REVIEW

**Comment by ratkosrb** [comment]
All the loot tables have the same structure because they share the same loading code.

**Comment by schell244** [comment]
Okay, in this case renaming makes no sense. Thank you.

**Comment by schell244** [comment]
@ratkosrb are you on discord? If you are ok with that, I would like to ask you a few questions regarding this project and it's dev process.

**Comment by schell244** [comment]
I'll do some more detailed research and rework this again.

**Pull request closed without merging**
