### PR TITLE
Std threading

### PR DESCRIPTION
**Pull request by WobLight**
Replacement of ACE threading stuff with std, last test was done aegis ago, merging to new code might have broke stuff...

There are tweaks to maps updates intervals.

### CODE REVIEW

**Comment by DarkmoonRabbit** [comment]
I think we should focus on game content fixes and version control! There is no point in modifying the underlying layer on a large scale This project is based on lh-server and has been proven for a long time in terms of operational efficiency and stability.

**Comment by ratkosrb** [comment]
@DarkmoonRabbit Pretty much every other modern emulation project has gotten rid of ACE. Why use an external dependency for features that are now part of the c++ standard language? I will make sure its tested and works fine before merging it.

**Comment by WobLight** [comment]
ACE is not entirely stripped by this, as it's used for networking and some other stuff. It's a first step though.
This code is older than lightshope itself (it was entering testing at that time), and was tested locally and in brotalnia's repack in the past.

**Comment by ulfgebhardt** [comment]
Hey @WobLight would you be willing to have another look and resolve the conflicts so we can push this forward? I believe its a valuable change to get rid of ACE! <3

**Comment by WobLight** [comment]
It compiles locally but I can't guarantee anything else, it may crash, deadlock and/or many other nasty things...

**Comment by ulfgebhardt** [comment]
Thanks a lot for your effort @WobLight  <3 - I will ask @ratkosrb to have another deep look - and maybe we can ask some server operators to use this branch with some players on it so we can push this forward.

**Comment by Oroxzy** [comment]
i tried and had no creatures spawned. flew around a little and some creatures appeared and disappeared if i was moving. however, it was not a clean database.

NVM works good so far with fresh DB!

**Comment by WobLight** [comment]
@ulfgebhardt mmm I don't see enough testing, just threat people saying you'll merge it as is :smirk:

**Comment by ulfgebhardt** [comment]
Hey @WobLight thanks for the update - I am afraid I don't have the power to merge and my threats would be laughed upon.
I am afraid we currently have no capacity to review and merge such a large PR - tho we intend to have this going at some point. I hope you don't mind that this is idle for the moment - and I am almost sure you will have to update the PR again at some point.
I am very sorry for this. Especially since the initial test from @Oroxzy has proven that there is very likely to be issues with this, I believe we need a larger team - which we are building up at the moment - and have a focused look on this at a given time.

<3

**Comment by ghost** [comment]
Gonna try this PR on Hyjal PTR

**Comment by ulfgebhardt** [comment]
@WobLight I talked to @brotalnia / @ratkosrb  about this - he said its fine to have this here, but as it does not remove the ACE dependency completely it would be too risky to merge this PR.
I think with @Nolin7777 wanting to test this new live comes into this and might change the situation, but could we have an estimation how much work it is to remove the ACE/TBB stuff completely?
Would you two work on it and get it merged?
Whats the opinion of @ratkosrb regarding @Nolin7777 taking responsibility here for a merge?

On the bright side: We are running out of PRs - soon only this one is left ;)

<3

**Comment by WobLight** [comment]
> he said its fine to have this here, but as it does not remove the ACE dependency completely it would be too risky to merge this PR.

This and that are separate issues. This pr is about threading, and has nothing to do with the rest of ACE code (network stuff).
Also, making addition changes like networking code would greatly increase debugging effort, so it's really a no go. This has to be tested and merged first.
Also, phasing out ACE will require another library to be used, as there's no standard network.

P.S.: note that this pr is not just refactoring, it also includes some optimizations to the threading logics.

**Comment by ulfgebhardt** [comment]
@WobLight Don't get me wrong, I am totally for merging this and advocated for it - I just wanted to bring you up to speed what the answer from brotalnia was and maybe spark the discussion with the involved parties how we gonna get this in the core. <3

**Comment by ratkosrb** [comment]
We can merge it once it has been sufficiently tested by Nolin with a lot of people online. But this work would be a lot more meaningful if it was a step on the way towards removing ACE completely and reducing amount of dependencies by the project.

**Comment by WobLight** [comment]
@Nolin7777 said it got tested with ~100 players peak, no crashes/deadlocks and nothing weird got reported.

**Comment by ulfgebhardt** [comment]
@ratkosrb can we move it forward? 2018... its about time 

image

**Comment by ratkosrb** [comment]
I never expected there to be issues with 100 online. That kind of load has been tested before. These changes were included in multiple repacks. The question was does it downgrade performance with the kind of population LH had for example. Makes no sense to me to merge it right before Nolin's server launches, and risk discovering it causes issues at that scale and having to revert it in 2 days. Impatience never leads to anything good, would be silly to fumble it in the final stretch.

**Comment by ghost** [comment]
I would consider this PR as ready to merge.

**Comment by Thorsten42** [comment]
Hi, this pr causes a segfault on exit in the movemapextractor, see #1123

**Pull request merged**
