### PR TITLE
Update readme with travis matrix badge status

### PR DESCRIPTION
**Pull request by coolzoom**
- ~~Update travis with make install~~ edit: incuded in the pr#781 by tonymmm1
- Updates readme with travis matrix badge https://github.com/bjfish/travis-matrix-badges

example

image

### CODE REVIEW

**Comment by tonymmm1** [comment]
Yeah looks good thanks for the addition although I dont know if the make install portion is strictly necessary since its really just compiling but I guess testing the install directive is fine.

**Comment by coolzoom** [comment]
> Yeah looks good thanks for the addition although I dont know if the make install portion is strictly necessary since its really just compiling but I guess testing the install directive is fine.

Yup, "make install" not quite necessary but no harm to have it, just incase someday we may mess around the cmake file and damage the cmake install copy-to-destination function. I did such mistake before the make was good but install was broken lol.

**Comment by tonymmm1** [comment]
I was thinking of maybe updating the ACE package to 6.5.11 could you maybe change it for me :smile:. There are two variable in the .travis.yml.

**Comment by tonymmm1** [comment]
Nevermind I can make a separate pull request to update TBB and ACE.

**Comment by coolzoom** [comment]
> Nevermind I can make a separate pull request to update TBB and ACE.

All right, that case we can match the pr with the title. we can fix conflict if there is any. or maybe i can just update the readme file and let you handle the .travis.yml.

**Comment by tonymmm1** [comment]
Sure I can add your Travis changes to my pr then, it should already be visible.

**Comment by tonymmm1** [comment]
Can you add those changes to my pr and remove them from this pr then it should be easy for merging and you will have credit for the commit.

**Comment by coolzoom** [comment]
> Can you add those changes to my pr and remove them from this pr then it should be easy for merging and you will have credit for the commit.

All right i have removed the change of .travis.yml you should be good to go

**Comment by tonymmm1** [comment]
ok changes have been committed.

**Pull request merged**
