### PR TITLE
Correct various outdoor waypoints.

### PR DESCRIPTION
**Pull request by Daribon**
## 🍰 Pullrequest

- Add waypoints to Ironeye the Invincible.
- Spawn new Salt Flats Vulture with waypoints
- Correct waypoints Dragonmaw Battlemaster.
- Correct waypoints for Flesh Golem in Andorhal. Old waypoints were guessed.
- Correct waypoints for Gish the Unmoving. Old waypoints were guessed.
- Add waypoints to Magronos the Unyielding.
- Correct waypoints for Teremus the Devourer. Old waypoints were guessed.
- Correct waypoints for Lord Kazzak, was previously missing several waypoints and waittime.
- Add random movement to Manahounds around The Dark Portal
- Add waypoints to Servant of Grol at Dreadmaul Post.
- Correct waypoints for Twilight Lord Everun. Old waypoints were guessed.
- Correct waypoints for Twilight Keeper Havunth. Old waypoints were guessed.
- Add waypoints to Twilight Keeper Exeter.
- Correct waypoints for Argent Dawn Infantry in EPL. Previously patrol had one path each and was guessed.
- Correct random movement, waypoints and spawns for several Twilight Avenger/Geolord in Silithus.
- Correct waypoints for Simone the Inconspicuous. Old waypoints were guessed. Deleted custom scripts.

Some images showing changes:
Before:
nomacs_19XY3t8C0A
After:
Wow_SkzMnh4zS8
Before:
WoW_PkvLfnOfFY
After:
Wow_uDOVj64y41
Before:
WoW_3AEBmG6fUQ
After:
Wow_2Tx5qJlGlB
Before:
WoW_kE4vQZgbtc
After:
Wow_7PyalDTAmf
Before:
WoW_anu7QCx132
After:
Wow_qjBBhYlFj5

### Proof

- All of it sniffed during two days on 1.15.0 PTR around 2 weeks before SoD launch.

### Issues

- None

### How2Test

- None

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by ratkosrb** [comment]
Dragonmaw Battlemaster waypoints were not custom, i added them based on sniffs.
https://github.com/vmangos/core/commit/28c089a283afb5770994a599cc7072f4fac6dd7a

**Comment by ShiyoKozuki** [comment]
How do you see blue glowing orbs for waypoints?

**Comment by Daribon** [comment]
> Dragonmaw Battlemaster waypoints were not custom, i added them based on sniffs. [28c089a](https://github.com/vmangos/core/commit/28c089a283afb5770994a599cc7072f4fac6dd7a)

None of the waypoints in that commit matches anything in my sniff. Example: 
firefox_vSBEPZZl9V

It should use points instead of waypoint from parse. In the commit above it has no waypoints placed ontop of it eachother, the NPC should have same path back.

Waypoint_Creator_v02KXwqgDk
For example point 23: 
EmEditor_qU9UJwnq6x
And later point 45:
EmEditor_ORZtyNiMJ8

**Comment by Daribon** [comment]
> How do you see blue glowing orbs for waypoints?

.wp show on

**Comment by ratkosrb** [comment]
Untitled

**Comment by ratkosrb** [comment]
Untitled

**Pull request merged**
