### PR TITLE
Kirtonos Script

### PR DESCRIPTION
**Pull request by Oroxzy**
Everything in this Video
https://www.youtube.com/watch?v=eFFJDFQJOeQ

### CODE REVIEW

**Comment by Oroxzy** [comment]
a btw i forgot to add an sql file to set Kirtonos movement_type to 0

**Comment by ratkosrb** [comment]
Can you replace those tabs with 4 spaces please?

**Comment by Oroxzy** [comment]
sure

**Comment by Oroxzy** [comment]
UPDATE `creature_template` SET `movement_type`='0' WHERE `entry`=10506;

is also required.

**Comment by alexkulya** [comment]
<pre>
UPDATE `creature_template` SET `ai_name` = "", `movement_type` = 0, `script_name` = "boss_kirtonos_the_herald" WHERE `entry` = 10506;
DELETE FROM `creature_ai_events` WHERE `creature_id` = 10506;
DELETE FROM `creature_ai_scripts` WHERE `id` IN (1050601, 1050602, 1050603, 1050604, 1050605, 1050606, 1050607, 1050608, 1050609, 1050610, 1050611, 1050612, 1050613);
</pre>

**Comment by ratkosrb** [comment]
I have improved the db script based on your pull request, since i would like to avoid moving scripts to the core if it's possible to do the same thing in the database. There should be no difference in game, so let me know if something is wrong. I have also made him despawn on death as is blizzlike.

**Pull request closed without merging**
